"""One request, end to end, through the deployed configuration.

    startup -> resolve target -> save -> run -> record -> reopen -> export

Every seam here was proven separately, and the chain still had two defects that
only appeared when a real request ran against a real PostgreSQL database:

    `WorkspaceStore()` never read `QUANTIFY_DATABASE_URL`, so the preflight
    validated PostgreSQL and the application wrote to a local SQLite file

    `worksheet_for_scenario` used SQLite's `json_extract`, which PostgreSQL
    does not have, so the query failed on every deployed request

Both passed every unit test. Neither was a wrong belief about a component; both
were two correct components disagreeing about what they were doing. That is
what a journey test is for, and it is why this one exists rather than more
seam tests.

**It fails by observing absent rows.** Restoring the store defect must make
this test notice that PostgreSQL holds nothing, not merely that two URLs
differ — the URL comparison lives in `test_store_target.py`, and a journey that
only repeated it would prove nothing new.
"""
from __future__ import annotations

import os
import sqlite3
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from src.market_data.provenance import ProvenanceStatus, from_json

POSTGRES_URL = os.environ.get("QUANTIFY_TEST_POSTGRES_URL")

pytestmark = pytest.mark.skipif(
    not POSTGRES_URL,
    reason="the journey runs against the deployed engine; SQLite cannot "
           "evidence that the configured target is the one opened")

OWNER = "pilot"
#: Set by the `journey` fixture from the redirect. The identity is generated by
#: the server now: the confirmation form once hardcoded `plan_id=my-plan`, so a
#: user could never save a second plan, and deriving one from the title would
#: have broken every run and worksheet reference the moment a title was edited.
PLAN_ID = ""
LOCAL_FALLBACK = Path("data/workspace.db")

DESCRIPTION = ("I put $2,000 into SPY every month in my Roth IRA, on the first "
               "trading day of the period, reinvesting the dividends, and I "
               "never sell.")


def migrated():
    from sqlalchemy import text

    from src.db import migrate
    from src.db.engine import Database

    database = Database(POSTGRES_URL)
    engine = database.sqlalchemy_engine()
    with engine.begin() as connection:
        connection.execute(text("DROP SCHEMA public CASCADE"))
        connection.execute(text("CREATE SCHEMA public"))
    engine.dispose()
    migrate.upgrade(database)
    return database


@pytest.fixture
def journey(monkeypatch):
    """Walk the real front door with the deployment pointed at PostgreSQL."""
    monkeypatch.setenv("PILOT_DATA_POLICY", "SYNTHETIC_ONLY")
    monkeypatch.setenv("QUANTIFY_DEPLOYMENT_PROFILE", "local")
    monkeypatch.setenv("QUANTIFY_DATABASE_URL", POSTGRES_URL)
    migrated()

    import src.api as api

    from tests.conftest import submit_rendered_confirmation

    global PLAN_ID
    with TestClient(api.app) as client:
        drafted = client.get("/workspace/new", params={"describe": DESCRIPTION})
        assert drafted.status_code == 200, drafted.status_code
        # Through the rendered form, like a browser. The old call posted
        # `describe` and `plan_id` as query parameters with `confirm_all` in
        # the body — a contract that no longer exists, and one that never
        # exercised the confirmation screen at all.
        saved, PLAN_ID = submit_rendered_confirmation(
            client, DESCRIPTION, title="Journey plan")
        assert saved.status_code == 303, (
            f"the front door did not commit: {saved.status_code} "
            f"{saved.text[:400]}")
        assert PLAN_ID and PLAN_ID.startswith("plan-")
    return saved


def fresh_store():
    """A store of its own, so nothing here is an artifact of the request."""
    from src.workspace.store import WorkspaceStore

    return WorkspaceStore(POSTGRES_URL)


def stored_runs(store):
    return [run for plan in store.list_plans(OWNER)
            for run in store.runs_for(plan["plan_id"], OWNER)]


def forbid_resolver(monkeypatch):
    import src.market_data.access as access

    def refuse(*args, **kwargs):
        raise AssertionError(
            "the resolver was called while reading stored state; the "
            "provenance should have come from the record")

    monkeypatch.setattr(access, "resolve", refuse)
    monkeypatch.setattr(access, "resolve_prices", refuse)


class TestTheRequestReachedTheConfiguredDatabase:
    """The regression that interrupted this test being written."""

    def test_the_plan_is_in_postgresql(self, journey):
        store = fresh_store()
        assert store.db.dialect.value == "postgresql"
        assert [plan["plan_id"] for plan in store.list_plans(OWNER)] == [PLAN_ID]

    def test_a_run_is_in_postgresql(self, journey):
        assert stored_runs(fresh_store()), (
            "no run reached the configured database; the request wrote "
            "somewhere else")

    def test_a_worksheet_is_in_postgresql(self, journey):
        store = fresh_store()
        assert store.worksheet_for_scenario(PLAN_ID, OWNER) is not None, (
            "no worksheet reached the configured database — this query used "
            "SQLite's `json_extract`, which PostgreSQL does not have, and "
            "failed on every deployed request")

    def test_nothing_material_went_to_the_local_fallback(self, journey):
        """Where the rows went when the store ignored its configuration."""
        if not LOCAL_FALLBACK.exists():
            return
        conn = sqlite3.connect(LOCAL_FALLBACK)
        try:
            rows = conn.execute(
                "SELECT COUNT(*) FROM plan WHERE plan_id = ?",
                (PLAN_ID,)).fetchone()[0]
        except sqlite3.OperationalError:
            return                       # no such table: nothing was written
        finally:
            conn.close()
        assert rows == 0, (
            f"{rows} row(s) for this journey are in the local SQLite fallback. "
            "The request wrote to a database the deployment did not configure")


class TestEveryStoredFigureIsAttributable:
    def test_no_run_claims_an_unrecorded_provenance(self, journey):
        for run in stored_runs(fresh_store()):
            carried = from_json(run["result"].get("market_data"))
            assert carried.status is ProvenanceStatus.RECORDED, (
                f"{run['run_id']} was stored without attribution; a live "
                "producer may not claim historical absence")

    def test_every_run_identifies_its_data(self, journey):
        for run in stored_runs(fresh_store()):
            carried = from_json(run["result"].get("market_data"))
            assert carried.identifies_data, run["run_id"]
            assert carried.content_digest, run["run_id"]

    def test_every_run_carries_an_allowed_decision(self, journey):
        for run in stored_runs(fresh_store()):
            carried = from_json(run["result"].get("market_data"))
            assert carried.permitted, run["run_id"]
            assert carried.access_decision is not None

    def test_all_seven_fields_are_present(self, journey):
        for run in stored_runs(fresh_store()):
            carried = from_json(run["result"].get("market_data"))
            assert carried.snapshot_id
            assert carried.content_digest
            assert carried.content_digest_version
            assert carried.license_class
            assert carried.policy_version
            assert carried.access_decision
            assert carried.accessed_at

    def test_the_cited_runs_agree_on_the_data(self, journey):
        """SHARED_ACCESS: one resolution, and every cited run proven to agree
        rather than assumed to because a loop shared an object."""
        records = [from_json(run["result"].get("market_data"))
                   for run in stored_runs(fresh_store())]
        assert records
        assert len({one.snapshot_id for one in records}) == 1
        assert len({one.content_digest for one in records}) == 1
        assert len({one.access_decision for one in records}) == 1
        assert len({one.policy_version for one in records}) == 1

    def test_the_worksheet_holds_a_reference_not_a_copy(self, journey):
        record = fresh_store().worksheet_for_scenario(PLAN_ID, OWNER)
        assert record is not None
        assert "market_data" not in str(record["payload"]), (
            "the worksheet carries its own provenance copy; one figure now has "
            "two sources of truth")
        assert record["payload"]["primary_run_ref"]


class TestReadingStoredStateResolvesNothing:
    def test_reopening_does_not_call_the_resolver(self, journey, monkeypatch):
        store = fresh_store()
        forbid_resolver(monkeypatch)
        assert store.list_plans(OWNER)
        assert store.worksheet_for_scenario(PLAN_ID, OWNER) is not None
        assert stored_runs(store)

    def test_exporting_does_not_call_the_resolver(self, journey, monkeypatch):
        from src.db.transfer import export_bundle

        store = fresh_store()
        forbid_resolver(monkeypatch)
        bundle = export_bundle(store, exported_at="2026-08-01T00:00:00Z")
        assert bundle["manifest"]["counts"]["plan_run"] >= 1

    def test_the_export_carries_the_stored_provenance(self, journey,
                                                      monkeypatch):
        from src.db.transfer import export_bundle

        store = fresh_store()
        before = [from_json(run["result"].get("market_data")).snapshot_id
                  for run in stored_runs(store)]
        forbid_resolver(monkeypatch)
        bundle = export_bundle(store, exported_at="2026-08-01T00:00:00Z")
        carried = [from_json(run["result"].get("market_data")).snapshot_id
                   for run in bundle["records"]["plan_run"]]
        assert carried == before


class TestTheChainSurvivesTheDeploymentMoving:
    def test_a_policy_change_does_not_rewrite_a_stored_run(self, journey,
                                                           monkeypatch):
        before = [from_json(run["result"].get("market_data")).to_json()
                  for run in stored_runs(fresh_store())]
        assert before

        monkeypatch.setenv("PILOT_DATA_POLICY",
                           "market-data-egress/pilot-vendor-approved@1")
        forbid_resolver(monkeypatch)

        after = [from_json(run["result"].get("market_data")).to_json()
                 for run in stored_runs(fresh_store())]
        assert after == before


class TestAMixedProvenanceSetIsVisible:
    """Proves the journey checks every cited run, not only the first."""

    def test_a_divergent_run_breaks_the_agreement(self, journey):
        from src.db.types import Json

        store = fresh_store()
        runs = stored_runs(store)
        assert runs

        forged = dict(runs[0]["result"])
        forged["market_data"] = {**forged["market_data"],
                                 "snapshot_id": "a-different-snapshot",
                                 "content_digest": "mdv1:different"}
        # Below the store: the writer would refuse this, which is the point.
        with store._conn() as conn:
            conn.execute("UPDATE plan_run SET result = ? WHERE run_id = ?",
                         (Json(forged), runs[0]["run_id"]))

        records = [from_json(run["result"].get("market_data"))
                   for run in stored_runs(fresh_store())]
        assert "a-different-snapshot" in {one.snapshot_id for one in records}, (
            "a divergent cited run went unnoticed")


class TestTheStoredRunCitesTheDeliveryItConsumed:
    """The gap this closed: a stored run cited what its *producer declared*.

    Declared provenance and a delivery record fail differently. Provenance is
    reusable — two runs under one policy carry identical records — so it cannot
    distinguish "this run received this frame" from "this run was written by
    code that believed it had". The event is the delivery itself, digested by
    the resolver over the frame it returned.
    """

    def events(self, store):
        with store._conn() as conn:
            return [dict(row) for row in conn.execute(
                "SELECT * FROM market_data_access_event WHERE owner = ?",
                (OWNER,)).fetchall()]

    def test_the_run_cites_a_delivery(self, journey):
        for run in stored_runs(fresh_store()):
            assert run["access_event_id"], (
                f"{run['run_id']} reached PostgreSQL citing no delivery; its "
                "only evidence is its own producer's claim")

    def test_the_delivery_is_in_postgresql(self, journey):
        store = fresh_store()
        assert self.events(store), "no delivery record reached the database"

    def test_the_chain_verifies(self, journey):
        store = fresh_store()
        for run in stored_runs(store):
            assert store.verify_access_chain(run["run_id"], OWNER) == [], (
                f"{run['run_id']} does not verify against its delivery")

    def test_the_delivery_names_the_run_it_was_resolved_for(self, journey):
        """Allocated before computation, so no second write binds them."""
        store = fresh_store()
        runs = {run["run_id"] for run in stored_runs(store)}
        named = {event["run_id"] for event in self.events(store)
                 if event["run_id"]}
        assert named & runs, (
            "no delivery names the run it was made for; the identity was "
            "allocated after computation and bound afterwards")

    def test_the_execution_input_matched_the_delivery(self, journey):
        """`resolved_frame_digest -> execution_input_digest -> result`.

        The delivery digest proves the resolver returned these rows. This
        proves the engine was handed those rows and not something they had
        become on the way.
        """
        for run in stored_runs(fresh_store()):
            scope = run["result"].get("modelling_scope") or {}
            assert scope.get("execution_input_digest"), run["run_id"]
            assert scope["execution_input_matches_delivery"] is True, (
                f"{run['run_id']} simulated a frame that is not the one it was "
                "delivered; the transformation between them is undeclared")

    def test_the_stored_digest_is_the_resolver_digest(self, journey):
        """Recomputed from the snapshot, so the stored value is checked against
        the data rather than against itself.

        Recomputed **using the request the event records**, which is the whole
        point and was the defect. This asked for the default resolution and
        compared it against a plan that reinvests dividends — a price-return
        frame against a total-return digest. It failed, and it read as
        "resolution is not deterministic", which would have condemned the
        snapshot-by-hash design. Resolution was deterministic; the recomputation
        was asking a different question.

        A verifier must therefore never spell the request itself. It replays
        what was recorded, so the day a resolution parameter is added this stops
        agreeing rather than silently reproducing with a default.
        """
        from src.market_data.access import resolve
        from src.market_data.access_event import (frame_digest, from_json)

        store = fresh_store()
        for stored in self.events(store):
            event = from_json(stored)
            assert event.reproducible, (
                f"{event.access_event_id} records no resolution request, so "
                "its digest cannot be checked against the data")
            replayed = resolve(context="verification",
                               **event.resolution.as_arguments())
            assert frame_digest(replayed.frame) == event.frame_digest, (
                "replaying the recorded request did not reproduce the stored "
                "digest, so the delivery record does not identify the data")

    def test_the_recorded_request_is_what_the_plan_asked_for(self, journey):
        """The plan reinvests dividends, so the record must say so.

        Without this the test above passes on a record that is merely
        self-consistent: an event claiming `reinvested=False` replays to its own
        wrong digest perfectly well. What makes the record evidence is that it
        agrees with the plan somebody actually wrote.
        """
        from src.market_data.access_event import from_json

        assert "reinvesting the dividends" in DESCRIPTION
        for stored in self.events(fresh_store()):
            assert from_json(stored).resolution.reinvested is True, (
                "the plan reinvests dividends and the delivery record says it "
                "did not, so the stored digest describes a frame the run was "
                "never given")

    def test_the_other_request_would_not_have_verified(self, journey):
        """The mutation, without which none of this discriminates.

        If both values of the request produced the same frame, recording it
        would be ceremony. They do not, and this says so in the same place the
        claim is made rather than in a unit test about a loader.
        """
        from src.market_data.access import resolve
        from src.market_data.access_event import frame_digest, from_json

        stored = next(iter(self.events(fresh_store())))
        recorded = from_json(stored).resolution
        other = resolve(context="verification",
                        **{**recorded.as_arguments(),
                           "reinvested": not recorded.reinvested})
        assert frame_digest(other.frame) != stored["frame_digest"], (
            "both resolutions produce the same frame, so recording which one "
            "was asked for proves nothing")


class TestOneResolutionIsOneDelivery:
    """SHARED_ACCESS: candidates compared against each other must have been
    measured on the same data, and citing separate deliveries would say they
    were not."""

    def test_every_run_cites_the_same_delivery(self, journey):
        cited = {run["access_event_id"] for run in stored_runs(fresh_store())}
        assert len(cited) == 1, (
            f"{len(cited)} deliveries across runs that share one resolution; "
            "comparing figures drawn from different deliveries is the thing "
            "the fan-out assumes cannot happen")

    def test_one_delivery_row_exists(self, journey):
        store = fresh_store()
        with store._conn() as conn:
            count = conn.execute(
                "SELECT COUNT(*) AS n FROM market_data_access_event "
                "WHERE owner = ?", (OWNER,)).fetchone()["n"]
        assert count == 1, f"{count} delivery rows for one resolution"


class TestReadingNeverReDigests:
    def test_reopening_does_not_recompute_a_digest(self, journey, monkeypatch):
        """Reopening must read the stored delivery, not re-derive one. A
        re-derived digest would silently agree with whatever is configured now,
        which is the failure verification exists to catch."""
        import src.market_data.access_event as event_module

        store = fresh_store()
        monkeypatch.setattr(event_module, "frame_digest", _refuse)
        assert store.list_plans(OWNER)
        for run in stored_runs(store):
            assert store.verify_access_chain(run["run_id"], OWNER) == []

    def test_exporting_does_not_recompute_a_digest(self, journey, monkeypatch):
        import src.market_data.access_event as event_module

        from src.db.transfer import export_bundle

        store = fresh_store()
        monkeypatch.setattr(event_module, "frame_digest", _refuse)
        bundle = export_bundle(store, exported_at="2026-08-01T00:00:00Z")
        assert bundle["manifest"]["counts"]["market_data_access_event"] >= 1


def _refuse(*args, **kwargs):
    raise AssertionError(
        "a digest was recomputed while reading stored state; the answer must "
        "come from the record")


class TestTamperingBreaksTheChain:
    def test_an_edited_delivery_is_detected(self, journey):
        store = fresh_store()
        runs = stored_runs(store)
        assert runs
        with store._conn() as conn:
            conn.execute(
                "UPDATE market_data_access_event SET frame_digest = ? "
                "WHERE owner = ?", ("mdf1:swapped-after-the-fact", OWNER))
        problems = store.verify_access_chain(runs[0]["run_id"], OWNER)
        assert any("edited since it was written" in one for one in problems)

    def test_the_delivery_cannot_be_deleted_while_a_run_cites_it(self, journey):
        """RESTRICT, on the deployed engine. A stored figure must not become
        unverifiable because something else was deleted."""
        store = fresh_store()
        assert stored_runs(store)
        # Asserted on SQLSTATE rather than on an exception class: the driver
        # raises `psycopg.errors.ForeignKeyViolation` here and
        # `sqlite3.IntegrityError` on the unit lane, and a test that named one
        # class would pass on one engine while proving nothing on the other.
        with pytest.raises(Exception) as refusal:               # noqa: PT011
            with store._conn() as conn:
                conn.execute(
                    "DELETE FROM market_data_access_event WHERE owner = ?",
                    (OWNER,))
        assert getattr(refusal.value, "sqlstate", "23503") == "23503", (
            f"the delete failed for something other than the constraint: "
            f"{type(refusal.value).__name__}")
        # And still there afterwards, so the refusal was a refusal rather than
        # a partial delete that raised on its way out.
        assert _events(store)

    def test_a_policy_change_does_not_alter_the_stored_delivery(self, journey,
                                                                 monkeypatch):
        store = fresh_store()
        before = [dict(row) for row in _events(store)]
        monkeypatch.setenv("PILOT_DATA_POLICY",
                           "market-data-egress/pilot-vendor-approved@1")
        after = [dict(row) for row in _events(fresh_store())]
        assert after == before


def _events(store):
    with store._conn() as conn:
        return conn.execute(
            "SELECT * FROM market_data_access_event WHERE owner = ?",
            (OWNER,)).fetchall()
