"""The migrations and the model must describe the same schema.

A migration system whose migrations have drifted from the model is worse than
none: it reports a schema version, the version is wrong, and every consumer
believes it. So the parity check does not read the migration scripts — it runs
them against an empty database and asks Alembic to diff the *result* against
`src/db/schema.py`. A non-empty diff is a failure.

`compare_metadata` is the same comparison `alembic revision --autogenerate`
uses. Reimplementing it here would produce a second opinion that could agree
with the model for reasons the real autogenerate does not share.

The check runs on SQLite unconditionally, and additionally on PostgreSQL when
one is reachable — PostgreSQL is where the deployed schema lives, and SQLite
passing is not evidence about JSONB, constraints or collations.
"""
from __future__ import annotations

import os

import pytest
from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext

from src.db import migrate
from src.db.engine import Database
from src.db.schema import metadata

POSTGRES_URL = os.environ.get("QUANTIFY_TEST_POSTGRES_URL")


def diff_against_model(database: Database):
    """What Alembic would put in the next autogenerated revision."""
    engine = database.sqlalchemy_engine()
    try:
        with engine.connect() as connection:
            context = MigrationContext.configure(
                connection,
                opts={"compare_type": True,
                      "render_as_batch": connection.dialect.name == "sqlite"})
            return compare_metadata(context, metadata)
    finally:
        engine.dispose()


def ignorable(diff) -> bool:
    """Differences that are rendering noise rather than schema drift.

    SQLite has no native boolean or server-default introspection worth
    comparing, and Alembic reports a `server_default` difference for
    `evidence_refs` that both sides in fact agree on. Nothing here hides a
    table, a column, an index or a type change.
    """
    if isinstance(diff, tuple) and diff and diff[0] == "modify_default":
        return True
    return False


@pytest.fixture
def sqlite_database(tmp_path):
    return Database(tmp_path / "migrated.db")


@pytest.fixture
def postgres_database():
    if not POSTGRES_URL:
        pytest.skip("set QUANTIFY_TEST_POSTGRES_URL to run against PostgreSQL")
    database = Database(POSTGRES_URL)
    engine = database.sqlalchemy_engine()
    from sqlalchemy import text
    with engine.begin() as connection:
        connection.execute(text("DROP SCHEMA public CASCADE"))
        connection.execute(text("CREATE SCHEMA public"))
    engine.dispose()
    return database


class TestTheHistoryIsUsable:
    def test_there_is_exactly_one_head(self):
        """Branched history has no single 'current schema' to check against."""
        assert migrate.code_head()

    def test_the_head_is_not_invented(self):
        """It comes from the scripts, so a build with none cannot claim one."""
        from alembic.script import ScriptDirectory
        script = ScriptDirectory.from_config(migrate.alembic_config())
        assert migrate.code_head() in {r.revision for r in script.walk_revisions()}


class TestFreshMigrationMatchesTheModel:
    """Run every migration from an empty database, then diff the result."""

    def test_on_sqlite(self, sqlite_database):
        migrate.upgrade(sqlite_database)
        drift = [d for d in diff_against_model(sqlite_database) if not ignorable(d)]
        assert drift == [], f"migrations and model disagree: {drift}"

    def test_on_postgresql(self, postgres_database):
        migrate.upgrade(postgres_database)
        drift = [d for d in diff_against_model(postgres_database)
                 if not ignorable(d)]
        assert drift == [], f"migrations and model disagree: {drift}"

    def test_every_modelled_table_exists_after_migrating(self, sqlite_database):
        migrate.upgrade(sqlite_database)
        present = set(sqlite_database.existing_tables())
        assert set(metadata.tables) <= present


class TestDowngrade:
    def test_the_baseline_reverses(self, sqlite_database):
        """A migration that cannot be undone is a deployment with no way back."""
        migrate.upgrade(sqlite_database)
        assert "plan" in sqlite_database.existing_tables()
        migrate.downgrade(sqlite_database, "base")
        remaining = set(sqlite_database.existing_tables()) - {"alembic_version"}
        assert remaining == set(), f"downgrade left {remaining} behind"


class TestTheStartupCheck:
    def test_an_unmigrated_database_is_refused(self, tmp_path):
        """Never-migrated and out-of-date need different remedies, so they are
        reported differently rather than both as 'wrong version'."""
        database = Database(tmp_path / "empty.db")
        assert migrate.applied_revision(database) is None
        with pytest.raises(migrate.MigrationMismatch, match="never been migrated"):
            migrate.require_migration_head(database)

    def test_a_stale_database_is_refused(self, sqlite_database):
        migrate.upgrade(sqlite_database)
        migrate.stamp(sqlite_database, "base")
        # Stamped to base: the version table exists but holds no revision.
        assert migrate.applied_revision(sqlite_database) is None
        with pytest.raises(migrate.MigrationMismatch):
            migrate.require_migration_head(sqlite_database)

    def test_a_current_database_starts(self, sqlite_database):
        migrate.upgrade(sqlite_database)
        assert migrate.require_migration_head(sqlite_database) == migrate.code_head()

    def test_the_reported_head_is_the_applied_one(self, sqlite_database):
        migrate.upgrade(sqlite_database)
        assert migrate.applied_revision(sqlite_database) == migrate.code_head()


class TestTheManifestReportsTheRealHead:
    """`QUANTIFY_MIGRATION_HEAD` used to be a variable nothing produced."""

    def test_the_manifest_head_comes_from_the_migrations(self):
        from src.deploy.manifest import code_versions
        assert code_versions()["migration_head"] == migrate.code_head()

    def test_it_is_no_longer_asked_of_the_environment(self):
        """A hand-set value can disagree with the migrations it describes."""
        from src.deploy.manifest import REQUIRED_DEPLOYMENT_FACTS
        assert "QUANTIFY_MIGRATION_HEAD" not in REQUIRED_DEPLOYMENT_FACTS

    def test_it_stays_out_of_the_public_view(self):
        """It describes how to attack the deployment, not how to talk to it."""
        from src.deploy.manifest import read_manifest
        assert "migration_head" not in read_manifest({}).public()


class TestStartupActuallyReachesTheCheck:
    """A declared control that the live path does not call is not a control."""

    def test_startup_refuses_an_unmigrated_database(self, monkeypatch,
                                                    postgres_database):
        from fastapi.testclient import TestClient

        import src.api as api

        monkeypatch.setenv("QUANTIFY_DATABASE_URL", postgres_database.url)
        # The schema was dropped and never migrated: starting would fail later,
        # on a user's request, in whichever code path got there first.
        with pytest.raises(migrate.MigrationMismatch):
            with TestClient(api.app):
                pass

    def test_startup_succeeds_once_migrated(self, monkeypatch,
                                            postgres_database):
        from fastapi.testclient import TestClient

        import src.api as api

        migrate.upgrade(postgres_database)
        monkeypatch.setenv("QUANTIFY_DATABASE_URL", postgres_database.url)
        with TestClient(api.app) as client:
            assert client.get("/health").status_code == 200
