"""own runs and plans by tenant

Revision ID: 7d37e87ad210
Revises: a6cc8a7fe5a0
Create Date: 2026-08-03 08:40:51.067203

`plan` was keyed on `plan_id` alone, so two tenants could not hold the same
plan id. `plan_run` had no owner at all and was reachable only through its
plan, which made every ownership question a join and left deletion one
forgotten cascade away from keeping every run while reporting success.

The data step is why this is hand-written rather than autogenerated.
`plan_run.owner` is added nullable, populated by joining through `plan`, and
*verified* before it is made NOT NULL: a run whose plan is missing, or a plan
id already held by two owners, would otherwise be assigned an owner by
whichever row the join happened to return. This refuses instead. An ownership
migration that guesses is worse than one that stops, because the guess is
invisible afterwards.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d37e87ad210'
down_revision: Union[str, Sequence[str], None] = 'a6cc8a7fe5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


class OwnershipUnresolved(RuntimeError):
    """A row's owner could not be established from the existing data."""


def _verify_every_run_resolves_one_owner(connection) -> None:
    """Refuse to continue unless every run maps to exactly one owner."""
    orphaned = connection.execute(sa.text(
        "SELECT COUNT(*) FROM plan_run WHERE owner IS NULL")).scalar()
    if orphaned:
        raise OwnershipUnresolved(
            f"{orphaned} run(s) name a plan that does not exist, so no owner "
            "can be established. Assigning one would invent a tenant "
            "relationship; resolve or remove these rows and migrate again.")

    ambiguous = connection.execute(sa.text(
        "SELECT COUNT(*) FROM (SELECT plan_id FROM plan "
        "GROUP BY plan_id HAVING COUNT(DISTINCT owner) > 1) AS d")).scalar()
    if ambiguous:
        raise OwnershipUnresolved(
            f"{ambiguous} plan id(s) already belong to more than one owner. "
            "The join that populates `plan_run.owner` cannot choose between "
            "them, and picking one would be invisible afterwards.")


def _rebuild_sqlite() -> None:
    """Rebuild `plan` and `plan_run` with the widened keys.

    Written out longhand. SQLite has no `ALTER ... PRIMARY KEY` and no way to
    replace a foreign key, so the only route is a new table, a copy, a drop and
    a rename — which is exactly what the three repair routines in `store.py`
    used to do by hand, now with an ordering and a recorded revision.
    """
    op.execute("PRAGMA foreign_keys = OFF")

    op.execute("ALTER TABLE plan RENAME TO plan__old")
    op.execute("""
        CREATE TABLE plan (
            plan_id      TEXT NOT NULL,
            owner        TEXT NOT NULL,
            title        TEXT NOT NULL,
            scenario     TEXT NOT NULL,
            intent       TEXT,
            stated_text  TEXT NOT NULL,
            saved_at     TEXT NOT NULL,
            rule_hash    TEXT NOT NULL,
            content_hash TEXT NOT NULL,
            parse        TEXT,
            PRIMARY KEY (plan_id, owner)
        )""")
    op.execute("""
        INSERT INTO plan (plan_id, owner, title, scenario, intent, stated_text,
                          saved_at, rule_hash, content_hash, parse)
        SELECT plan_id, owner, title, scenario, intent, stated_text, saved_at,
               rule_hash, content_hash, parse FROM plan__old""")
    op.execute("DROP TABLE plan__old")

    op.execute("ALTER TABLE plan_run RENAME TO plan_run__old")
    op.execute("""
        CREATE TABLE plan_run (
            owner      TEXT NOT NULL,
            run_id     TEXT NOT NULL,
            plan_id    TEXT NOT NULL,
            ran_at     TEXT NOT NULL,
            result     TEXT NOT NULL,
            comparison TEXT NOT NULL,
            PRIMARY KEY (owner, run_id),
            CONSTRAINT fk_plan_run_owner_plan_id
                FOREIGN KEY (owner, plan_id) REFERENCES plan (owner, plan_id)
                ON DELETE RESTRICT
        )""")
    op.execute("""
        INSERT INTO plan_run (owner, run_id, plan_id, ran_at, result, comparison)
        SELECT owner, run_id, plan_id, ran_at, result, comparison
        FROM plan_run__old""")
    op.execute("DROP TABLE plan_run__old")

    op.execute("PRAGMA foreign_keys = ON")


def upgrade() -> None:
    """Give runs an owner, then key both tables by tenant."""
    connection = op.get_bind()
    sqlite = connection.dialect.name == "sqlite"

    # 1. Nullable first, so existing rows survive the addition.
    with op.batch_alter_table("plan_run") as batch:
        batch.add_column(sa.Column("owner", sa.Text(), nullable=True))

    # 2. Populate from the only place the answer exists.
    op.execute(
        "UPDATE plan_run SET owner = (SELECT plan.owner FROM plan "
        "WHERE plan.plan_id = plan_run.plan_id)")

    # 3. Verify before committing to it. Everything below assumes this held.
    _verify_every_run_resolves_one_owner(connection)

    if sqlite:
        # SQLite cannot alter a key or a constraint in place, and batch mode
        # copies the *existing* constraints — which would have carried the old
        # single-column foreign key forward, leaving the migration and the
        # model disagreeing. Both tables are therefore rebuilt explicitly, with
        # the target shape written out here rather than imported: a migration
        # that read the current model would describe whatever the model means
        # today rather than what this revision did.
        _rebuild_sqlite()
        return

    # 4. The single-column foreign key has to go before `plan` can be rekeyed.
    op.drop_constraint("fk_plan_run_plan_id", "plan_run", type_="foreignkey")

    # 5. Widen both identities.
    op.alter_column("plan", "owner", existing_type=sa.Text(), nullable=False)
    op.drop_constraint("plan_pkey", "plan", type_="primary")
    op.create_primary_key("plan_pkey", "plan", ["plan_id", "owner"])

    op.alter_column("plan_run", "owner", existing_type=sa.Text(),
                    nullable=False)
    op.drop_constraint("plan_run_pkey", "plan_run", type_="primary")
    op.create_primary_key("plan_run_pkey", "plan_run", ["owner", "run_id"])

    # 6. A run now belongs to exactly one owner's plan by construction rather
    #    than by an application convention nothing enforced.
    op.create_foreign_key(
        "fk_plan_run_owner_plan_id", "plan_run", "plan",
        ["owner", "plan_id"], ["owner", "plan_id"], ondelete="RESTRICT")


def downgrade() -> None:
    """Narrow both identities again.

    Lossy by nature: two tenants holding one plan id cannot both survive a
    return to a single-column key, so this refuses rather than dropping one.
    """
    connection = op.get_bind()
    sqlite = connection.dialect.name == "sqlite"

    colliding = connection.execute(sa.text(
        "SELECT COUNT(*) FROM (SELECT plan_id FROM plan "
        "GROUP BY plan_id HAVING COUNT(*) > 1) AS d")).scalar()
    if colliding:
        raise OwnershipUnresolved(
            f"{colliding} plan id(s) are held by more than one owner. "
            "Narrowing the key would silently discard one tenant's plans.")

    if not sqlite:
        op.drop_constraint("fk_plan_run_owner_plan_id", "plan_run",
                           type_="foreignkey")
        op.drop_constraint("plan_run_pkey", "plan_run", type_="primary")
        op.create_primary_key("plan_run_pkey", "plan_run", ["run_id"])
        op.drop_constraint("plan_pkey", "plan", type_="primary")
        op.create_primary_key("plan_pkey", "plan", ["plan_id"])
        op.create_foreign_key("fk_plan_run_plan_id", "plan_run", "plan",
                              ["plan_id"], ["plan_id"], ondelete="RESTRICT")

    with op.batch_alter_table("plan_run") as batch:
        batch.drop_column("owner")
