"""baseline workspace schema

Revision ID: c7c7c8740ac7
Revises: 
Create Date: 2026-08-02 19:46:06.217660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c7c7c8740ac7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmation_event',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('field', sa.Text(), nullable=True),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('final_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('compiler_version', sa.Text(), nullable=True),
    sa.Column('defaults_ref', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('event_reconciliation',
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('worksheet_id', sa.Text(), nullable=False),
    sa.Column('reconciliation_id', sa.Text(), nullable=False),
    sa.Column('planned_event_id', sa.Text(), nullable=True),
    sa.Column('observed_event_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
    sa.Column('matching_policy_version', sa.Text(), nullable=False),
    sa.Column('superseded_by', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('derived_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('owner', 'worksheet_id', 'reconciliation_id')
    )
    op.create_index('reconciliation_worksheet', 'event_reconciliation', ['owner', 'worksheet_id', 'derived_at'], unique=False)
    op.create_table('observation',
    sa.Column('observation_id', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_table('observed_event',
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('worksheet_id', sa.Text(), nullable=False),
    sa.Column('observed_event_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.Text(), nullable=False),
    sa.Column('asset', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Text().with_variant(sa.Numeric(precision=38, scale=12), "postgresql"), nullable=True),
    sa.Column('value', sa.Text().with_variant(sa.Numeric(precision=38, scale=12), "postgresql"), nullable=True),
    sa.Column('payload', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
    sa.Column('evidence_refs', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('supersedes', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('owner', 'worksheet_id', 'observed_event_id')
    )
    op.create_table('plan',
    sa.Column('plan_id', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('scenario', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('stated_text', sa.Text(), nullable=False),
    sa.Column('saved_at', sa.Text(), nullable=False),
    sa.Column('rule_hash', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('parse', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('plan_run',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Text(), nullable=False),
    sa.Column('ran_at', sa.Text(), nullable=False),
    sa.Column('result', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
    sa.Column('comparison', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('planned_event',
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('worksheet_id', sa.Text(), nullable=False),
    sa.Column('planned_event_id', sa.Text(), nullable=False),
    sa.Column('plan_revision', sa.Integer(), nullable=False),
    sa.Column('grant_ref', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('expected_effective_date', sa.Text(), nullable=False),
    sa.Column('asset', sa.Text(), nullable=True),
    sa.Column('expected_quantity', sa.Text().with_variant(sa.Numeric(precision=38, scale=12), "postgresql"), nullable=True),
    sa.Column('expected_value', sa.Text().with_variant(sa.Numeric(precision=38, scale=12), "postgresql"), nullable=True),
    sa.Column('payload', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
    sa.Column('matching_policy_version', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('owner', 'worksheet_id', 'planned_event_id')
    )
    op.create_table('proposal',
    sa.Column('proposal_id', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
    sa.Column('generated_at', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('proposal_id')
    )
    op.create_table('worksheet',
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('worksheet_id', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
    sa.Column('canonical_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('owner', 'worksheet_id', 'revision')
    )
    op.create_table('worksheet_intent',
    sa.Column('intent_id', sa.Text(), nullable=False),
    sa.Column('worksheet_id', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('instruction_hash', sa.Text(), nullable=False),
    sa.Column('structured_request', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
    sa.Column('edit_effect', sa.Text(), nullable=False),
    sa.Column('selection_basis', sa.Text(), nullable=False),
    sa.Column('repetition_signature', sa.Text(), nullable=False),
    sa.Column('related_prior', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
    sa.Column('results_visible', sa.Integer(), nullable=False),
    sa.Column('alternatives', sa.Integer(), nullable=False),
    sa.Column('trial_effect', sa.Integer(), nullable=True),
    sa.Column('planner_version', sa.Text(), nullable=False),
    sa.Column('chain_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('proposal_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('intent_id')
    )
    op.create_index('worksheet_intent_sequence', 'worksheet_intent', ['worksheet_id', 'owner', 'sequence'], unique=True)
    op.create_table('worksheet_proposal',
    sa.Column('proposal_id', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('worksheet_id', sa.Text(), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.Text(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('result_revision', sa.Integer(), nullable=True),
    sa.Column('result_runs', sa.Text().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('proposal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worksheet_proposal')
    op.drop_index('worksheet_intent_sequence', table_name='worksheet_intent')
    op.drop_table('worksheet_intent')
    op.drop_table('worksheet')
    op.drop_table('proposal')
    op.drop_table('planned_event')
    op.drop_table('plan_run')
    op.drop_table('plan')
    op.drop_table('observed_event')
    op.drop_table('observation')
    op.drop_index('reconciliation_worksheet', table_name='event_reconciliation')
    op.drop_table('event_reconciliation')
    op.drop_table('confirmation_event')
    # ### end Alembic commands ###
