"""Mission: replaying what someone actually does, against history.

A methodology answers "given capital, what weights?". A Mission answers "given a
life, what transactions?" — which is why it accounts in shares and cash rather
than in weights, and why it reports both return bases instead of the one the
weight engine can produce.
"""
from .accounting import (
    CashFlow,
    Grant,
    CashPolicy,
    CashPolicyError,
    Fill,
    Order,
    PortfolioPath,
    money_weighted_return,
    time_weighted_returns,
)
from .benchmark import (
    BenchmarkComparison,
    FlowMismatch,
    buy_and_hold,
    compare,
    comparison_payload,
    hold_cash,
)
from .boundary import (
    PROHIBITED_KEYS,
    VISIBILITY,
    BoundaryViolation,
    Extraction,
    PrivacyLeak,
    UndeclaredVisibility,
    Visibility,
    check_all,
    check_reference,
    extract_rule,
    scan_for_personal_data,
    visibility_of,
)
from .comparability import (
    DISCLOSURES,
    DISCLOSURE_VERSION,
    ISOLATION_DIMENSIONS,
    ComparabilityVerdict,
    ComparisonClass,
    RunConditions,
    classify,
    classify_counterfactual,
)
from .compiler import (
    CompilerResult,
    Origin,
    ParsedUtterance,
    Recognition,
    compile_scenario,
    parse,
)
from .parse_model import (
    VOCABULARY,
    AnthropicClient,
    Disagreement,
    ModelClient,
    ParseProvenance,
    Rejection,
    VerifiedParse,
    build_system_prompt,
    parse_with_model,
    verify_proposals,
)
from .defaults import DEFAULT_SET, Default, DefaultSet
from .intent import (
    GENERATION_CONSTRAINTS,
    Candidate,
    CandidateOrigin,
    HiddenSelection,
    Intent,
    SelectionBasis,
)
from .recommendation import (
    Basis,
    Check,
    RecommendationAssessment,
    scan_language,
)
from .recommendation import assess as assess_recommendation
from .observation import (
    Deviation,
    DeviationKind,
    ExpectedEvent,
    LinkedSeriesRefused,
    ObservedEvent,
    PlanObservation,
    Segment,
    SegmentedPerformance,
    reconcile,
)
from .proposal import (
    Eligibility,
    ExecutionAttempted,
    ExecutionMode,
    Proposal,
    ProposalStatus,
    expire_overdue,
    lifecycle_summary,
)
from .scenario import (
    AllocationRule,
    BenchmarkSet,
    HoldingsPolicy,
    ScenarioSpecification,
)
from .simulate import MissionResult, simulate
from .spec import (
    MISSION_SPEC_VERSION,
    Contradiction,
    FlowSchedule,
    Inference,
    Mission,
    Objective,
    Provenance,
    Unresolved,
)

__all__ = [
    "DEFAULT_SET",
    "DISCLOSURES",
    "DISCLOSURE_VERSION",
    "GENERATION_CONSTRAINTS",
    "CompilerResult",
    "Default",
    "DefaultSet",
    "Origin",
    "ParsedUtterance",
    "Recognition",
    "compile_scenario",
    "parse",
    "VOCABULARY",
    "AnthropicClient",
    "Disagreement",
    "ModelClient",
    "ParseProvenance",
    "Rejection",
    "VerifiedParse",
    "build_system_prompt",
    "parse_with_model",
    "verify_proposals",
    "ISOLATION_DIMENSIONS",
    "MISSION_SPEC_VERSION",
    "PROHIBITED_KEYS",
    "AllocationRule",
    "Deviation",
    "DeviationKind",
    "Eligibility",
    "ExpectedEvent",
    "Grant",
    "LinkedSeriesRefused",
    "ObservedEvent",
    "Proposal",
    "ProposalStatus",
    "ExecutionAttempted",
    "ExecutionMode",
    "expire_overdue",
    "lifecycle_summary",
    "classify_counterfactual",
    "PlanObservation",
    "Segment",
    "SegmentedPerformance",
    "reconcile",
    "Basis",
    "BenchmarkSet",
    "CandidateOrigin",
    "ComparabilityVerdict",
    "ComparisonClass",
    "Check",
    "HiddenSelection",
    "HoldingsPolicy",
    "PrivacyLeak",
    "RecommendationAssessment",
    "RunConditions",
    "ScenarioSpecification",
    "assess_recommendation",
    "classify",
    "scan_for_personal_data",
    "scan_language",
    "VISIBILITY",
    "BenchmarkComparison",
    "BoundaryViolation",
    "Candidate",
    "Contradiction",
    "Extraction",
    "FlowSchedule",
    "Inference",
    "Intent",
    "Mission",
    "Objective",
    "Provenance",
    "SelectionBasis",
    "UndeclaredVisibility",
    "Unresolved",
    "Visibility",
    "check_all",
    "check_reference",
    "extract_rule",
    "visibility_of",
    "CashFlow",
    "CashPolicy",
    "CashPolicyError",
    "Fill",
    "FlowMismatch",
    "MissionResult",
    "Order",
    "PortfolioPath",
    "buy_and_hold",
    "compare",
    "comparison_payload",
    "hold_cash",
    "money_weighted_return",
    "simulate",
    "time_weighted_returns",
]
