"""ScenarioSpecification — the layer between what someone said and what runs.

Compiling an Intent straight into a Methodology would be a category error: the
personal event program is not an investment methodology. "Buy $2,000 of these six
names when SPY closes below its 200-day average, and never sell" contains a
market rule, a money path, and an evaluation choice, tangled together. Only the
first is a methodology; the second is nobody's research and the third is a
protocol.

    Intent
      ↓
    ScenarioSpecification        the whole thing, with provenance
      ↓
    Methodology + EvaluationProtocol + FlowSchedule

Keeping them separate is what lets the same rule be tested under someone else's
contributions without claiming the two people had the same financial outcome —
and it is what makes `extract_rule` a clean seam rather than a redaction pass.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Sequence

from .spec import FlowSchedule, MISSION_SPEC_VERSION, Objective, Provenance


def _hash(payload: Mapping[str, Any]) -> str:
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode()
    ).hexdigest()


@dataclass(frozen=True)
class AllocationRule:
    """What the money buys, and how it is divided.

    `weighting` distinguishes the two readings of "equally" that a user will not:
    equal dollars at purchase never needs a sale, equal weight thereafter needs
    one on every drift. Conflating them is how "never sell" and "equally" end up
    silently contradicting each other.
    """

    assets: Sequence[str]
    weighting: str = "equal_weight_at_purchase"

    def canonical_form(self) -> Dict[str, Any]:
        return {"assets": sorted(self.assets), "weighting": self.weighting}


@dataclass(frozen=True)
class HoldingsPolicy:
    sells_allowed: bool = True
    rebalancing_allowed: bool = True

    def canonical_form(self) -> Dict[str, Any]:
        return {"sells_allowed": self.sells_allowed,
                "rebalancing_allowed": self.rebalancing_allowed}


@dataclass(frozen=True)
class BenchmarkSet:
    """Declared before results, generated by a published rule.

    `generated_by_rule` names a public policy artifact rather than describing one
    inline, so the set a user was shown can be reconstructed later — the same
    reason a run records its policy id rather than its verdict alone.
    """

    generated_by_rule: str
    members: Sequence[str] = ()
    ordering: str = "unordered"

    def canonical_form(self) -> Dict[str, Any]:
        return {"generated_by_rule": self.generated_by_rule,
                "members": sorted(self.members), "ordering": self.ordering}


@dataclass(frozen=True)
class ScenarioSpecification:
    """Everything the user described, separated into what each layer owns."""

    name: str
    version: int
    objective: Objective
    event_program: Sequence[Dict[str, Any]]
    flow_schedule: FlowSchedule
    allocation_rule: AllocationRule
    holdings_policy: HoldingsPolicy = field(default_factory=HoldingsPolicy)
    cash_policy_ref: str = ""
    benchmark_set: Optional[BenchmarkSet] = None
    provenance: Provenance = field(default_factory=Provenance)
    intent_ref: Optional[str] = None
    pending_template: Optional[str] = None
    """A life-event template that will supply the flows once filled in. While it
    is pending, an empty flow schedule is incomplete rather than contradictory —
    complaining that there is no money to invest would be describing the wrong
    problem, and would send the reader to fix something that is not broken."""

    tax_treatment: str = "NONE_APPLIED"
    spec_version: str = MISSION_SPEC_VERSION

    @property
    def concept_id(self) -> str:
        return f"scenario/{self.name}"

    @property
    def artifact_id(self) -> str:
        return f"scenario/{self.name}@{self.version}"

    def self_conflicts(self) -> List[str]:
        """Contradictions the structure exposes that prose hides.

        The compiler should already have caught these from the text. This catches
        them from the compiled form, which is the version that actually runs — and
        a check that only reads the input trusts the compiler to have been right.
        """
        conflicts: List[str] = []
        maintains_weight = self.allocation_rule.weighting == "equal_weight_maintained"

        # These two are one conflict seen from two sides, and a confirmation
        # screen listing it twice reads as carelessness. The selling form is
        # reported because it names the mechanism: what the plan would have to
        # do that the user forbade.
        if maintains_weight and not self.holdings_policy.sells_allowed:
            conflicts.append(
                "holdings_policy forbids selling while allocation_rule maintains "
                "equal weight; maintaining a weight requires selling what rose"
            )
        elif maintains_weight and not self.holdings_policy.rebalancing_allowed:
            conflicts.append(
                "allocation_rule maintains equal weight while rebalancing is "
                "forbidden"
            )
        if (self.flow_schedule.amount <= 0
                and self.flow_schedule.starting_capital <= 0
                and not self.pending_template):
            conflicts.append(
                "no contributions and no starting capital: there is no money to "
                "invest, so every figure would be undefined rather than zero"
            )
        return conflicts

    @property
    def is_runnable(self) -> bool:
        return not self.self_conflicts()

    # ---- the split into the three artifacts that execute ------------------

    def methodology_part(self) -> Dict[str, Any]:
        """The market rule alone — impersonal, and the only part that could ever
        become public research."""
        return {
            "pipeline": [step.get("action", step.get("observe", "step"))
                         for step in self.event_program],
            "event_program": list(self.event_program),
            "allocation_rule": self.allocation_rule.canonical_form(),
            "holdings_policy": self.holdings_policy.canonical_form(),
        }

    def protocol_part(self) -> Dict[str, Any]:
        """How it is evaluated. Shared with the library's protocols by design."""
        return {"cash_policy_ref": self.cash_policy_ref,
                "tax_treatment": self.tax_treatment,
                "benchmark_set": (self.benchmark_set.canonical_form()
                                  if self.benchmark_set else None)}

    def flow_part(self) -> Dict[str, Any]:
        """The money path. Never public, and never part of the rule."""
        return self.flow_schedule.canonical_form()

    def canonical_form(self) -> Dict[str, Any]:
        return {
            "spec_version": self.spec_version,
            "name": self.name,
            "version": self.version,
            "objective": self.objective.value,
            "methodology": self.methodology_part(),
            "protocol": self.protocol_part(),
            "flows": self.flow_part(),
            "inferred": sorted(
                ({"field": i.field, "value": i.value}
                 for i in self.provenance.inferred),
                key=lambda d: d["field"],
            ),
        }

    @property
    def content_hash(self) -> str:
        return _hash(self.canonical_form())

    @property
    def rule_hash(self) -> str:
        """Identity of the market rule alone.

        Two people running the same rule on different salaries share this and
        differ in `content_hash`, which is exactly the distinction the comparison
        classes turn on.
        """
        return _hash(self.methodology_part())

    def to_json(self) -> Dict[str, Any]:
        return {
            **self.canonical_form(),
            "artifact_id": self.artifact_id,
            "concept_id": self.concept_id,
            "content_hash": self.content_hash,
            "rule_hash": self.rule_hash,
            "intent_ref": self.intent_ref,
            "provenance": self.provenance.to_json(),
            "self_conflicts": self.self_conflicts(),
            "is_runnable": self.is_runnable,
        }
